# Generated by Django 5.1.4 on 2025-01-01 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_remove_file_created_at_remove_file_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 1, 17, 25, 14, 986523, tzinfo=datetime.timezone.utc)),
        ),
    ]
