# Generated by Django 5.1.4 on 2025-01-01 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_file_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 1, 18, 58, 36, 552448, tzinfo=datetime.timezone.utc)),
        ),
    ]
