# Generated by Django 5.1.4 on 2025-01-05 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_alter_file_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 5, 16, 4, 14, 411355, tzinfo=datetime.timezone.utc)),
        ),
    ]
